Final hook up
HootFS/hootfs pull request #16
Opened 2021-10-27 04:59 UTC by chathamabate

2021-11-01 21:00 UTC, josh8551021 requested changes
Mostly good. A bunch a small things about comments taking up too many lines, plus a few nits.

2021-11-05 20:15 UTC, josh8551021 commented on src/core/file_storage/file_system_manager.go
> +		return nil, err
I don't think we actually want this to fail. This is a case of lazy file creation. The file doesn't actually exist on disk until someone writes to it. So when someone requests the contents of an empty file, we just return an empty byte slice.

2021-11-05 20:19 UTC, josh8551021 reviewed
LGTM. I'll hold off on approval until I revert the change in `file_system_manager.go`

2021-11-05 20:48 UTC, josh8551021 approved these changes

2021-11-05 21:31 UTC, Landmaster approved these changes

2021-11-06 20:03 UTC, merged