Auth0 middleware
HootFS/hootfs pull request #27
Opened 2021-12-02 22:03 UTC by gamebot770

### Purpose
Hooks in middleware that will allow for Auth0 to authenticate any and all requests sent to hootfs. 

### Details
Authenticated users will have their information stored in the context under the key "userInfo". 
Currently will only hold a string representing the user's email. Can add more information upon request.

### Modifications required to other parts of codebase
No code changes will be required anywhere else in the codebase. Verifier is wrapped in the google_verifer package

2021-12-03 20:59 UTC, Landmaster commented
Shouldn't .idea/workspace.xml be gitignored?

2021-12-03 21:17 UTC, josh8551021 requested changes
Looks good, just a couple of things.

2021-12-03 21:17 UTC, josh8551021 commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
nit: remove JetBrains workspace file.

2021-12-03 21:17 UTC, josh8551021 commented on src/core/auth/google_verifier.go
> +	//for key, value := range result {
nit: remove this commented code

2021-12-03 21:17 UTC, josh8551021 commented on src/core/hootfs/head_node.go
> +	print("Server started")
Should this be another `log.println()` call?

2021-12-03 21:17 UTC, josh8551021 commented on src/core/auth/google_verifier.go
> +func New(url string) Google_verifier {
You should probably return a pointer here, as the `Google_verifier` struct could technically grow in size.

2021-12-03 21:17 UTC, josh8551021 commented on src/core/auth/google_verifier.go
> +	if username == result["email"].(string) {
You should probably check for existence of "email" field, just to be safe.

2021-12-03 21:17 UTC, josh8551021 commented on src/core/auth/google_verifier.go
> +func (g Google_verifier) Authenticate(ctx context.Context) (context.Context, error) {
Similar to above, you should probably define this function for a `Google_verifier` pointer, same with all other functions.

2021-12-03 21:23 UTC, josh8551021 commented on README.md
> +##Debug Instructions for GoLand
Add space here so that header shows up properly. Same with line 4.

2021-12-03 21:49 UTC, josh8551021 commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Maybe add `.idea/` to gitignore?

2021-12-03 21:50 UTC, josh8551021 approved these changes
LGTM, just remove the `workspace.xml` file from the repo before merging.

2021-12-06 17:39 UTC, chathamabate approved these changes
LGTM.

2021-12-06 19:10 UTC, Landmaster approved these changes
should be fine now that workspace xml is not in commit

2021-12-06 19:10 UTC, merged