Add file manager and head node server skeleton code
HootFS/hootfs pull request #5
Opened 2021-10-04 20:35 UTC by josh8551021

Add skeleton code for necessary core libraries.

2021-10-04 20:46 UTC, chathamabate commented
Please add CreateDirectory

2021-10-04 22:08 UTC, chathamabate commented
LGTM @Landmaster please review this soon so we can get this merged.

2021-10-04 22:09 UTC, chathamabate approved these changes

2021-10-05 23:58 UTC, Landmaster requested changes
Please fix your indentation in head.proto, some of the defs have 5-space instead of 4-space indents.

2021-10-06 00:04 UTC, merged